environment:
  matrix:
    - PYTHON: "C:\\Python34"

install:
 - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
 - python --version
 - "pip install -r requirements.txt"

build: false

test_script:
 - "python setup.py test"
